/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"

void clock_init()
{
	RCC_GPIOA_CLK_EN(); //enable clock for portA
	RCC_GPIOB_CLK_EN(); //enable clock for portB

}

void GPIO_init()
{
	GPIO_PinConfig_t PinCfg;
	//PA1 input highZ floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_Mode_Input_Flo;
	MCAL_GPIO_INIT(GPIOA, &PinCfg);

	//PB1 output push pull
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_Mode_Output_PP;
	PinCfg.GPIO_Output_Speed = Output_Speed_10M;
	MCAL_GPIO_INIT(GPIOB, &PinCfg);

	//PA13 input highZ floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_Mode_Input_Flo;
	MCAL_GPIO_INIT(GPIOA, &PinCfg);

	//PB13 output push pull
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_Mode_Output_PP;
	PinCfg.GPIO_Output_Speed = Output_Speed_10M;
	MCAL_GPIO_INIT(GPIOB, &PinCfg);

}
void wait_ms(uint32_t time)
{
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clock_init();
	GPIO_init();
	/* Loop forever */
	while(1)
		{
			if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0)
			{
				MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
				while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0); //single pressing
			}
			if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1) //multi pressing
				MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
			wait_ms(1);
		}
}
