/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>

#define RCC_BASE 0x40021000
#define PORTA_BASE 0x40010800

#define RCC_APB2ENR  *(volatile uint32_t *) (RCC_BASE + 0x18)
#define GPIO_CRH     *(volatile uint32_t *) (PORTA_BASE + 0x04)
#define GPIO_ODR 	 *(volatile uint32_t *) (PORTA_BASE + 0x0C)
#define GPIOA_CRL 	 *(volatile uint32_t *) (PORTA_BASE + 0x0C)



//EXTI
#define EXTI_bASE  0x40010400
#define EXTI_IMR 	 *(volatile uint32_t *) (EXTI_bASE + 0x00)
#define EXTI_RTSR 	 *(volatile uint32_t *) (EXTI_bASE + 0x08)
#define EXTI_PR 	 *(volatile uint32_t *) (EXTI_bASE + 0x14)

//AFIO
#define AFIO_bASE  0x40010000
#define AFIO_EXTICR1 	 *(volatile uint32_t *) (AFIO_bASE + 0x08)

//NVIC
#define NVIC_EXTIE0 	 *(volatile uint32_t *) (0xE000E100)




void Clock_init()
{
	//Enable clock GPIOA
	RCC_APB2ENR |= (1<<2); //set bit2 (only bit 2)
	// EXTI clock is Enabled by Default

	//Enable AFIO (Alternative Function I/O)
	RCC_APB2ENR |= (1<<0);

}

void GPIO_INIT()
{
	//pin13 portA is output
	GPIO_CRH &= 0xff0fffff; //clear bits from 20 to 24
	GPIO_CRH |= 0x00200000; // put value 2 (0010) to bits from 20 to 24

	//pin0 portA is floating input
	GPIOA_CRL |= (1<<2);
}


int main(void)
{
	Clock_init();
	GPIO_INIT();

	//Enable interrupt when Rising trigger
	EXTI_RTSR |= (1<<0);

	//Enable EXTI Line 0 (Mask 1)
	EXTI_IMR |= (1<<0);

	//EXTI0 configuration to portA0
	AFIO_EXTICR1 |= (0<<0);

	//Enable NVIC IRQ >>> EXTI0 (From IVT(interrupt vrctor table))
	NVIC_EXTIE0 |= (1<<6);


	/* Loop forever */
	while(1);
}

void EXTI0_IRQHandler(void)
{
	GPIO_ODR ^= (1<<13); // toggle led

	//Clear Pending Request by set Pending Request of line 0 by 1
	EXTI_PR |= (1<<0);
}
